const menu = [
    {
        title:'首页',
        icon:'home',
        items:[],
        path:'/home'
    },
    {
        title:'写博客',
        icon:'book',
        items:[],
        path:'/blog'
    },
    {
        title:'分类',
        icon:'appstore',
        items:['java','javascript','node.js'],
        path:'/category'
    },
    {
        title:'标签',
        icon:'tags',
        items:['生活','科技','文学'],
        path:'/tags'
    },
    {
        title:'我的',
        icon:'user',
        items:[],
        path:'/mine'
    }
]
export default menu;